+ first commit sprint 12
Triapkin/java-filmorate-new pull request #3
Opened 2024-08-12 22:10 UTC by Triapkin

2024-08-13 20:46 UTC, z8q requested changes

2024-08-13 20:46 UTC, z8q commented on src/main/resources/application.properties
> +spring.datasource.password=password
можно еще добавить сюда spring.h2.console.enabled=true
после запуска подключиться к базе http://localhost:8080/h2-console
посмотреть, что происходит

например, если пользователь поставит несколько раз лайк на один и тот же фильм, в базе сохранятся несколько записей

2024-08-13 20:46 UTC, z8q commented on src/main/resources/schema.sql
> +    user_id bigint
похоже тоже нужен будет PRIMARY KEY (film_id, user_id)

только на повторных попытках поставить лайк будет приходить ошибка с кодом 500
и будет возвращаться внутренний sql запрос
```JSON
{
	"error": "Исключения",
	"description": "PreparedStatementCallback; SQL [INSERT INTO likes(film_id, user_id) VALUES(?,?)]; Unique index or primary key violation: \"PUBLIC.PRIMARY_KEY_4 ON PUBLIC.LIKES(FILM_ID, USER_ID) VALUES ( /* key:1 */ CAST(1 AS BIGINT), CAST(1 AS BIGINT))\"; SQL statement:\nINSERT INTO likes(film_id, user_id) VALUES(?,?) [23505-224]"
}
```

Можно обработать исключения в exception handler

К вызову метода добавления в друзья тоже применимо

2024-08-13 20:46 UTC, z8q commented on src/main/resources/schema.sql
> +    mpa_Id      bigint
для id, которые являются foreign key, стоит еще указывать reference на таблицу, например
mpa_Id bigint REFERENCES mpa_type(id)

Еще станет важен порядок выполнения команд по созданию таблиц,
создание mpa_type нужно будет перенести выше

2024-08-13 20:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +            jdbc.update(INSERT_FILM_GENRES, filmId, genre.getId());
есть зависимость количества запросов к базе от размера списка genres,
можно попробовать сократить, посмотреть, как работать с jdbcTemplate.batchUpdate

2024-08-13 20:46 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Можно на поле friends поставить `@JsonIgnore`, если при get запросах это поле не заполняется

2024-08-13 21:18 UTC, Triapkin commented on src/main/resources/application.properties
> +spring.datasource.password=password
спасибо, понятно

2024-08-13 21:22 UTC, Triapkin commented on src/main/resources/schema.sql
> +    user_id bigint
добавил PRIMARY KEY (film_id, user_id), создал эксепшен хендлер на DuplicateKeyException, статус выбрал 409 по описанию из https://www.rfc-editor.org/rfc/rfc7231#section-6.5.8 (+почитал на стэковерфлоу), в description указал текст "Такая запись уже сущесвует" (я так понял основная идея, скрыть sql запрос)

2024-08-13 21:27 UTC, Triapkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
добавил

2024-08-13 21:37 UTC, Triapkin commented on src/main/resources/schema.sql
> +    mpa_Id      bigint
спасибо, исправил schema.sql

2024-08-13 21:45 UTC, Triapkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +            jdbc.update(INSERT_FILM_GENRES, filmId, genre.getId());
спасибо, переписал на batchUpdate

2024-08-14 18:27 UTC, z8q approved these changes

2024-08-14 19:29 UTC, merged